"""SQLAlchemy ORM models for Requirements, Monitors, and Alerts."""

from datetime import datetime, timezone
from sqlalchemy import Boolean, Column, DateTime, Float, ForeignKey, Integer, String, Text
from sqlalchemy.orm import relationship
from ramma_backend.database import Base


def utc_now():
    return datetime.now(timezone.utc)


class Requirement(Base):
    """SQLAlchemy model for storing interpreted ML monitoring requirements."""

    __tablename__ = "requirements"

    id = Column(Integer, primary_key=True, index=True, autoincrement=True)
    raw_text = Column(String, nullable=False)
    metric = Column(String, nullable=False)
    operator = Column(String, nullable=False)
    threshold = Column(Float, nullable=False)
    severity = Column(String, nullable=False)
    is_ambiguous = Column(Boolean, nullable=False, default=False)
    ambiguity_reason = Column(String, nullable=True)
    created_at = Column(DateTime(timezone=True), default=utc_now, nullable=False)

    monitors = relationship("Monitor", back_populates="requirement", cascade="all, delete-orphan")


class Monitor(Base):
    """SQLAlchemy model for monitoring configurations linked to a requirement."""

    __tablename__ = "monitors"

    id = Column(Integer, primary_key=True, index=True, autoincrement=True)
    requirement_id = Column(Integer, ForeignKey("requirements.id"), nullable=False)
    config_json = Column(Text, nullable=True)
    created_at = Column(DateTime(timezone=True), default=utc_now, nullable=False)

    requirement = relationship("Requirement", back_populates="monitors")
    alerts = relationship("Alert", back_populates="monitor", cascade="all, delete-orphan")


class Alert(Base):
    """SQLAlchemy model for alerts generated by monitors."""

    __tablename__ = "alerts"

    id = Column(Integer, primary_key=True, index=True, autoincrement=True)
    monitor_id = Column(Integer, ForeignKey("monitors.id"), nullable=False)
    observed_value = Column(Float, nullable=False)
    is_violation = Column(Boolean, nullable=False)
    explanation = Column(Text, nullable=False)
    contributors_json = Column(Text, nullable=True)
    created_at = Column(DateTime(timezone=True), default=utc_now, nullable=False)

    monitor = relationship("Monitor", back_populates="alerts")
